# file.yaml

input_filename: "./testdata/MUP_PHY_R22_P05_V10_D20_Geo.csv"
input_filetype: "csv"
dump_throttle: 10
dump_header: off
column_delimiter: ","
number_of_columns: 15
findings_filename: "findings.txt"

options:
  - test:
      name: Rndrng_Prvdr_Geo_Lvl
      regex: "National"
  - test:
      name: Avg_Mdcr_Alowd_Amt
      regex: '/^-?\d+(,\d{3})*(\.\d{1,2})?$/'
