# file.yaml

input_filename: "./testdata/feature_test.csv"
input_filetype: "csv"
dump_throttle: 0
dump_header: True
dump_config: True
column_delimiter: ","
number_of_columns: 6
findings_filename: "test_data_findings.txt"

options:
  - test: 
      name: number_type
  - test:
      name: date_type
      type: date
  - test: 
      name: money_format
      type: money   
  - test:
      name: required_col
  - test:
      name: range_col
  - test:
      name: regex_choice
      regex: "^National$|^State$"